spring:
  datasource:
    url: ${H2_URL}
    username: ${H2_USERNAME}
    password: 

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

twilio:
  sid: ${TWILIO_SID}
  key: ${AUTH_TOKEN}
  phone:
    from: ${TWILIO_PHONE_FROM}
    to: ${TWILIO_PHONE_TO}
